[client]
showSidebarNavigation = false
[theme]
primaryColor = "#f50d4bff"
textColor = "#0f325a"
baseFontSize=12
backgroundColor =  "#ffffffff"
font = "sans serif"
[server]
runOnSave = true
fileWatcherType = "poll"
